### ISSUE TITLE
Improve plugin config strategy

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana-config#17]
Improve config of plugins so that the config items are accessed in the same way regardless of if the plugin is started as Hapi plugin or as a standalone app.

**Comment by patriciagarcia** [comment]
@jo, @gr2m is this still relevant?

**Comment by gr2m** [comment]
yes, it is. I'll add more information to the issue, it's a tricky one

**Comment by gr2m** [comment]
The additional challenge we have with kazana is that all plugins can be started in separated processes. And apps can be registered as plugins, too. Which is cool, but makes configuration hard.

So if I have a main app, with a `.kazanarc` file like 

```
...
[plugin.weather-app]
  location: berlin
```

Then I want `{location: berlin}` to be passed to the `weather-app` module. But the module can be loaded all in one process using `npm start`, or it can be started in a separated process. 

I'll make a test case for this. I think we with the `--only=weather-app` cli argument that should be pretty straight forward, we could use the `[plugin.weather-app]` name space as config route, or merge it with the root config.

**Comment by jo** [comment]
This is relevant for implementing a `maxBytes` hapi upload limit config option.

**Comment by gr2m** [comment]
The answer to life, the universe, and config namespaces: #42

**Comment by gr2m** [comment]
released as [5.4.0](https://github.com/eHealthAfrica/kazana-config/releases/tag/v5.4.0)
