### ISSUE TITLE
Timeout config ignored

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana-config#21]
`timeout` option is ignored, all the other config options are working
```
[plugin.kazana-email-box]
emailAccount = "mail@mail.com":etcetc@imap.gmail.com:993
cacheDirectory = ./file_cache
days = 7
timeout = 100000
pollingBreak = 100000
filenameFilter = (.+\.xls.?)|(.+\.zip)$
[log]
level = info
[backend]
timeout = 40000
```
Kazana-config version is 5.2.0

Also when `backend.location` is set : it does not use the directory configured but project root instead of the default

cc/ @lucidNTR

**Comment by lucidNTR** [comment]
kazana version is 6.3.2

**Comment by jo** [comment]
Closing in favor of https://github.com/eHealthAfrica/kazana/issues/73 and https://github.com/eHealthAfrica/kazana/issues/74
