### ISSUE TITLE
Support `backend: false` for in-memory pouchdb server

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana-config#24]
https://github.com/hoodiehq/spawn-pouchdb-server seems to allow using `--in-memory` option by passing `backend: false`.

We can accept that config in `kazana-config` `backend` and use it when starting the pouchdb server here: https://github.com/eHealthAfrica/kazana/blob/46404e89403057a11e7bba879bb1fa2b801b61be/bin/server#L40

**Comment by gr2m** [comment]
note that https://www.npmjs.com/package/rc interprets

```
backend=false
```

as

```
backend="false" // string, not boolean
```

which is a bit inconsistent as `--backend=false` works fine ([minimist](https://www.npmjs.com/package/minimist) is used to parse cli params). 

I wonder if we can parse the options from `kazanarc` files with the same thing that minimist uses

**Comment by jo** [comment]
you can pass a custom argv parser in rc: https://github.com/dominictarr/rc#pass-in-your-own-argv

**Comment by gr2m** [comment]
yes I know, what I meant is that `--backend=false` is interpreted as boolean, while `backend=false` in the config file gets interpreted as string, which caused already a few headaches, and I'm not sure what the best way is to normaliset that. Currently I do it on app level (https://github.com/eHealthAfrica/kazana/blob/master/bin/server#L41), I think it should happen in `kazana-config`, or even in `rc` itself

**Comment by jo** [comment]
This is currently possible via

```js
{
  backend: {
    name: 'memdown'
  }
}
```

**Comment by jo** [comment]
Also related:
https://github.com/eHealthAfrica/kazana-config/issues/27

We currently cannot simply pass `backend=false` because we have overloaded it with other config, eg `log`

**Comment by patriciagarcia** [comment]
@jo, can we close this? (is this solved by the other PR that set up the in memory option?)

**Comment by jo** [comment]
No, I think we should leave this open.

Depends on https://github.com/eHealthAfrica/kazana-config/issues/27.

**Comment by patriciagarcia** [comment]
Closing in favor of #27
