### ISSUE TITLE
.<name>rc -> .kazanarc

### ISSUE THREAD

**Issue by boennemann** [eHealthAfrica/kazana-config#4]
I don't know if there is any previous discussion on this, but I think this should just be a static `.kazanarc` file, because that's what you're configuring with this file. It's confusing when the same config file has different names for different projects.

**Comment by gr2m** [comment]
I thought it would make sense to have different config file names for different projects, so the rc config files don't interfere with each other. But there has been no discussion on this at all, and just hardcoding it to `.kazanarc` would make things much simpler :)

So let's say I have 3 apps based on kazana locally, when I think about it, it would actually make thinks simpler as I could configure my admin username / password in `/etc/.kazanarc`, and all new kazana apps would pick it up automatically, right?

And for deployment, all apps would live isolated anyway, so there should be no problem. 

@boennemann if you don't see any potential of conflicting config files across kazana apps, I'd change that as you suggest. Makes things even simpler, I love it

**Comment by boennemann** [comment]
@gr2m I don't see potential for conflict. And as you said, being able to specify general config in files outside of the app, and potentially for more than one app, is what makes rc so beautiful and flexible: `/etc/.kazanarc`, `~/.kazanrc.` etc.

**Comment by gr2m** [comment]
fixed via 
https://github.com/eHealthAfrica/kazana-config/commit/11bffd18f58a75d63d2ab82481bf3f59bd7204d4
